[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ez a rész megpróbálja elkerülni az Edge bundling hibákat
[functions]
  included_files = ["!middleware.js"]